### PR TITLE
Added additional information to instructions

### PR DESCRIPTION
**Pull request by DaveVoyles**

### CODE REVIEW

**Comment by cursey** [comment]
Installation doesn't require building the project. The instructions in the current `README.md` are all you actually need to do if you just want to run the latest build of the mod framework. Maybe split the sections so that there is one for installation and a separate one for building.

**Comment by DaveVoyles** [comment]
So the only step that needs to be removed is the  **install_vs2017.bat* by double clicking on it**, correct?

I was initially confused, but the instructions don't explain which files need to be included, where to place the files after unzip, or what the mod framework .dll does. 

I had to find a video on YouTube which explained instructions, and it said to run the install file.

**Comment by cursey** [comment]
No. All you need to do is download the zip from AppVeyor which just includes `dinput8.dll`. That's all you need to run the Mod Framework you do not need to download the repository unless you plan on building it (`install_vs2017.bat` is only necessary for building the project not installing the prebuilt AppVeyor binary).

**Comment by DaveVoyles** [comment]
Ah OK, thank you for clarifying. 

Could we add that to the instructions? I think many people will come here, thinking they have to download and unzip these files as well.

**Pull request closed without merging**
